from typing import Literal

from langchain_core.documents import Document
from typing_extensions import TypedDict


Intent = Literal[
    "faq",
    "normal",
    "out_of_scope",
]


class ChatState(TypedDict, total=False):
    """
    State shared between all nodes in the LangGraph workflow.
    """

    # Original user message
    user_message: str

    # Classified intent
    intent: Intent

    # Documents retrieved from the FAQ vector database
    retrieved_documents: list[Document]

    # Relevance score from the retrieval stage
    relevance_score: float

    # Whether the retrieved FAQ context is sufficient
    context_relevant: bool

    # Final response generated by the chatbot
    answer: str

    # Whether support contact information should be displayed
    contact_support: bool